spring:
  application:
    name: transporte
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestao_transporte?useTimezone=true&serverTimezone=UTC
    username: root
    password: oidu
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
 level:
  root: INFO
springdoc:
  paths-to-match: /**/**
  swagger-ui:
   use-root-path: true
